---
language: python
python: "2.7"

install:
  # Install Ansible.
  - pip install ansible

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/hosts tests/test.yml --syntax-check

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
