---
- hosts: raspberrypis
  vars:
    dashboard_url: http://www.bbc.co.uk/
  remote_user: pi
  sudo: true
  tasks:
  - name: Install Midori
    apt: name=midori update_cache=yes
  - name: Add breadcrumbs to old configs 1
    lineinfile: dest=/etc/xdg/lxsession/LXDE/autostart regexp="$" line="{{ '#' }} Look in ~/.config/lxsession/LXDE-pi/autostart"
  - name: Add breadcrumbs to old configs 2
    lineinfile: dest=/etc/xdg/lxsession/LXDE-pi/autostart regexp="$" line="{{ '#' }} Look in ~/.config/lxsession/LXDE-pi/autostart"
  - name: Insert new autostart config file
    template: src=files/autostart dest=/home/pi/.config/lxsession/LXDE-pi/autostart owner=pi group=pi mode=0644
  - name: Reboot the machine to let changes take effect
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
  - name: waiting for server to come back
    local_action: wait_for port=22 delay=20 host="{{ ansible_ssh_host | default(inventory_hostname) }}"
    sudo: false
